import re
import datetime
from pathlib import Path
from typing import List, Any, Optional

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

from config import REPORTS_DIR, BOT_NAME, BASE_DIR

# Register Bengali Unicode Font (Kalpurush)
DEFAULT_FONT = "Helvetica"
DEFAULT_FONT_BOLD = "Helvetica-Bold"

_font_path = BASE_DIR / "fonts" / "kalpurush.ttf"
if _font_path.exists():
    try:
        pdfmetrics.registerFont(TTFont("Kalpurush", str(_font_path)))
        DEFAULT_FONT = "Kalpurush"
        DEFAULT_FONT_BOLD = "Kalpurush"
    except Exception as e:
        print(f"Could not register Kalpurush font: {e}")

def _clean_text_for_pdf(text: str) -> str:
    """Escapes XML entities for ReportLab Paragraphs and converts bold markdown."""
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # Convert **bold** to <b>bold</b>
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    # Convert *italic* to <i>italic</i>
    text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
    return text

def generate_pdf_report(title: str, text_content: str, filename_prefix: str = "report") -> Path:
    """
    Generates an executive-quality PDF report using ReportLab.
    Supports English and Bengali seamlessly via Kalpurush Unicode font.
    Returns the Path to the generated PDF.
    """
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    sanitized_prefix = re.sub(r'[^\w\-]', '_', filename_prefix)[:20]
    file_path = REPORTS_DIR / f"{sanitized_prefix}_{timestamp}.pdf"

    doc = SimpleDocTemplate(
        str(file_path),
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    # Custom typography styles supporting Bengali & English
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName=DEFAULT_FONT_BOLD,
        fontSize=18,
        leading=24,
        textColor=colors.HexColor('#0F172A'),
        alignment=TA_LEFT,
        spaceAfter=6
    )

    meta_style = ParagraphStyle(
        'DocMeta',
        parent=styles['Normal'],
        fontName=DEFAULT_FONT,
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#64748B'),
        spaceAfter=12
    )

    heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName=DEFAULT_FONT_BOLD,
        fontSize=12,
        leading=17,
        textColor=colors.HexColor('#1E293B'),
        spaceBefore=12,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'BodyDark',
        parent=styles['Normal'],
        fontName=DEFAULT_FONT,
        fontSize=10,
        leading=15,
        textColor=colors.HexColor('#334155'),
        spaceAfter=6
    )

    bullet_style = ParagraphStyle(
        'BulletText',
        parent=styles['Normal'],
        fontName=DEFAULT_FONT,
        fontSize=10,
        leading=15,
        textColor=colors.HexColor('#334155'),
        leftIndent=15,
        spaceAfter=4
    )

    elements = []

    # 1. Header Banner
    now_str = datetime.datetime.now().strftime("%B %d, %Y - %I:%M %p")
    elements.append(Paragraph(_clean_text_for_pdf(title), title_style))
    elements.append(Paragraph(f"Generated by <b>{BOT_NAME} 24/7 AI</b> | Date: {now_str}", meta_style))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#3B82F6'), spaceAfter=14))

    # 2. Body Parsing (Markdown paragraphs, headings, bullets)
    lines = text_content.split("\n")
    for line in lines:
        raw_line = line.strip()
        if not raw_line:
            elements.append(Spacer(1, 6))
            continue

        if raw_line.startswith("### ") or raw_line.startswith("## ") or raw_line.startswith("# "):
            clean_head = raw_line.lstrip("#").strip()
            elements.append(Paragraph(_clean_text_for_pdf(clean_head), heading_style))
        elif raw_line.startswith("- ") or raw_line.startswith("* ") or raw_line.startswith("• "):
            bullet_content = raw_line[2:].strip()
            elements.append(Paragraph(f"• {_clean_text_for_pdf(bullet_content)}", bullet_style))
        else:
            elements.append(Paragraph(_clean_text_for_pdf(raw_line), body_style))

    # 3. Footer Spacer
    elements.append(Spacer(1, 15))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#CBD5E1'), spaceAfter=8))
    footer_text = f"<i>Confidential - Prepared exclusively by {BOT_NAME} Assistant.</i>"
    elements.append(Paragraph(footer_text, meta_style))

    doc.build(elements)
    return file_path

def generate_excel_report(title: str, headers: List[str], data_rows: List[List[Any]], filename_prefix: str = "report") -> Path:
    """
    Generates a beautifully formatted Excel report using OpenPyXL.
    Returns the Path to the generated .xlsx file.
    """
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    sanitized_prefix = re.sub(r'[^\w\-]', '_', filename_prefix)[:20]
    file_path = REPORTS_DIR / f"{sanitized_prefix}_{timestamp}.xlsx"

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Summary Report"

    # Title Block
    ws.merge_cells("A1:E1")
    title_cell = ws["A1"]
    title_cell.value = f"{title} - {BOT_NAME} Report"
    title_cell.font = Font(name="Calibri", size=15, bold=True, color="FFFFFF")
    title_cell.fill = PatternFill(start_color="1E293B", end_color="1E293B", fill_type="solid")
    title_cell.alignment = Alignment(horizontal="left", vertical="center", indent=1)
    ws.row_dimensions[1].height = 32

    # Date Block
    ws.merge_cells("A2:E2")
    date_cell = ws["A2"]
    date_cell.value = f"Exported: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    date_cell.font = Font(name="Calibri", size=9, italic=True, color="64748B")
    date_cell.alignment = Alignment(horizontal="left", vertical="center", indent=1)
    ws.row_dimensions[2].height = 18

    # Headers Block (Row 4)
    header_fill = PatternFill(start_color="2563EB", end_color="2563EB", fill_type="solid")
    header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    thin_border = Border(
        left=Side(style='thin', color='E2E8F0'),
        right=Side(style='thin', color='E2E8F0'),
        top=Side(style='thin', color='E2E8F0'),
        bottom=Side(style='thin', color='CBD5E1')
    )

    for col_num, header in enumerate(headers, 1):
        cell = ws.cell(row=4, column=col_num)
        cell.value = str(header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center", vertical="center")
        cell.border = thin_border
    ws.row_dimensions[4].height = 24

    # Data Rows
    row_alt_fill = PatternFill(start_color="F8FAFC", end_color="F8FAFC", fill_type="solid")
    for r_idx, row_data in enumerate(data_rows, 5):
        is_even = (r_idx % 2 == 0)
        for c_idx, val in enumerate(row_data, 1):
            cell = ws.cell(row=r_idx, column=c_idx)
            cell.value = val
            cell.font = Font(name="Calibri", size=10)
            cell.border = thin_border
            if is_even:
                cell.fill = row_alt_fill
            cell.alignment = Alignment(horizontal="left", vertical="center")
        ws.row_dimensions[r_idx].height = 20

    # Auto-adjust column widths
    for col in ws.columns:
        max_len = max(len(str(cell.value or '')) for cell in col)
        col_letter = get_column_letter(col[0].column)
        ws.column_dimensions[col_letter].width = max(max_len + 4, 12)

    wb.save(str(file_path))
    return file_path
